//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class TTXClient {
  private http: {
    fetch(url: RequestInfo, init?: RequestInit): Promise<Response>;
  };
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(
    baseUrl?: string,
    http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> },
  ) {
    this.http = http ? http : window as any;
    this.baseUrl = baseUrl ?? "";
  }

  /**
   * @param page (optional)
   * @param limit (optional)
   * @param search (optional)
   * @param orderBy (optional)
   * @param orderDir (optional)
   * @return OK
   */
  getCreators(
    page?: number | undefined,
    limit?: number | undefined,
    search?: string | undefined,
    orderBy?: CreatorOrderBy | undefined,
    orderDir?: OrderDirection | undefined,
  ): Promise<CreatorDtoPaginationDto> {
    let url_ = this.baseUrl + "/creators?";
    if (page === null) {
      throw new globalThis.Error("The parameter 'page' cannot be null.");
    } else if (page !== undefined) {
      url_ += "page=" + encodeURIComponent("" + page) + "&";
    }
    if (limit === null) {
      throw new globalThis.Error("The parameter 'limit' cannot be null.");
    } else if (limit !== undefined) {
      url_ += "limit=" + encodeURIComponent("" + limit) + "&";
    }
    if (search === null) {
      throw new globalThis.Error("The parameter 'search' cannot be null.");
    } else if (search !== undefined) {
      url_ += "search=" + encodeURIComponent("" + search) + "&";
    }
    if (orderBy === null) {
      throw new globalThis.Error("The parameter 'orderBy' cannot be null.");
    } else if (orderBy !== undefined) {
      url_ += "orderBy=" + encodeURIComponent("" + orderBy) + "&";
    }
    if (orderDir === null) {
      throw new globalThis.Error("The parameter 'orderDir' cannot be null.");
    } else if (orderDir !== undefined) {
      url_ += "orderDir=" + encodeURIComponent("" + orderDir) + "&";
    }
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetCreators(_response);
    });
  }

  protected processGetCreators(
    response: Response,
  ): Promise<CreatorDtoPaginationDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = CreatorDtoPaginationDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<CreatorDtoPaginationDto>(null as any);
  }

  /**
   * @param username (optional)
   * @param ticker (optional)
   * @return OK
   */
  createCreator(
    username?: string | undefined,
    ticker?: string | undefined,
  ): Promise<ModelId> {
    let url_ = this.baseUrl + "/creators?";
    if (username === null) {
      throw new globalThis.Error("The parameter 'username' cannot be null.");
    } else if (username !== undefined) {
      url_ += "username=" + encodeURIComponent("" + username) + "&";
    }
    if (ticker === null) {
      throw new globalThis.Error("The parameter 'ticker' cannot be null.");
    } else if (ticker !== undefined) {
      url_ += "ticker=" + encodeURIComponent("" + ticker) + "&";
    }
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "POST",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processCreateCreator(_response);
    });
  }

  protected processCreateCreator(response: Response): Promise<ModelId> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = ModelId.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<ModelId>(null as any);
  }

  /**
   * @param before (optional)
   * @return OK
   */
  getCreator(slug: string, before?: string | undefined): Promise<CreatorDto> {
    let url_ = this.baseUrl + "/creators/{slug}?";
    if (slug === undefined || slug === null) {
      throw new globalThis.Error("The parameter 'slug' must be defined.");
    }
    url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
    if (before === null) {
      throw new globalThis.Error("The parameter 'before' cannot be null.");
    } else if (before !== undefined) {
      url_ += "before=" + encodeURIComponent("" + before) + "&";
    }
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetCreator(_response);
    });
  }

  protected processGetCreator(response: Response): Promise<CreatorDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = CreatorDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<CreatorDto>(null as any);
  }

  /**
   * @param reason (optional)
   * @return OK
   */
  optOutCreator(
    slug: string,
    reason?: string | undefined,
  ): Promise<CreatorOptOutDto> {
    let url_ = this.baseUrl + "/creators/{slug}?";
    if (slug === undefined || slug === null) {
      throw new globalThis.Error("The parameter 'slug' must be defined.");
    }
    url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
    if (reason === null) {
      throw new globalThis.Error("The parameter 'reason' cannot be null.");
    } else if (reason !== undefined) {
      url_ += "reason=" + encodeURIComponent("" + reason) + "&";
    }
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "DELETE",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processOptOutCreator(_response);
    });
  }

  protected processOptOutCreator(
    response: Response,
  ): Promise<CreatorOptOutDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = CreatorOptOutDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<CreatorOptOutDto>(null as any);
  }

  /**
   * @param page (optional)
   * @param limit (optional)
   * @param search (optional)
   * @param orderBy (optional)
   * @param orderDir (optional)
   * @return OK
   */
  getPlayers(
    page?: number | undefined,
    limit?: number | undefined,
    search?: string | undefined,
    orderBy?: PlayerOrderBy | undefined,
    orderDir?: OrderDirection | undefined,
  ): Promise<PlayerDtoPaginationDto> {
    let url_ = this.baseUrl + "/players?";
    if (page === null) {
      throw new globalThis.Error("The parameter 'page' cannot be null.");
    } else if (page !== undefined) {
      url_ += "page=" + encodeURIComponent("" + page) + "&";
    }
    if (limit === null) {
      throw new globalThis.Error("The parameter 'limit' cannot be null.");
    } else if (limit !== undefined) {
      url_ += "limit=" + encodeURIComponent("" + limit) + "&";
    }
    if (search === null) {
      throw new globalThis.Error("The parameter 'search' cannot be null.");
    } else if (search !== undefined) {
      url_ += "search=" + encodeURIComponent("" + search) + "&";
    }
    if (orderBy === null) {
      throw new globalThis.Error("The parameter 'orderBy' cannot be null.");
    } else if (orderBy !== undefined) {
      url_ += "orderBy=" + encodeURIComponent("" + orderBy) + "&";
    }
    if (orderDir === null) {
      throw new globalThis.Error("The parameter 'orderDir' cannot be null.");
    } else if (orderDir !== undefined) {
      url_ += "orderDir=" + encodeURIComponent("" + orderDir) + "&";
    }
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetPlayers(_response);
    });
  }

  protected processGetPlayers(
    response: Response,
  ): Promise<PlayerDtoPaginationDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = PlayerDtoPaginationDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<PlayerDtoPaginationDto>(null as any);
  }

  /**
   * @param before (optional)
   * @return OK
   */
  getPlayer(username: string, before?: string | undefined): Promise<PlayerDto> {
    let url_ = this.baseUrl + "/players/{username}?";
    if (username === undefined || username === null) {
      throw new globalThis.Error("The parameter 'username' must be defined.");
    }
    url_ = url_.replace("{username}", encodeURIComponent("" + username));
    if (before === null) {
      throw new globalThis.Error("The parameter 'before' cannot be null.");
    } else if (before !== undefined) {
      url_ += "before=" + encodeURIComponent("" + before) + "&";
    }
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetPlayer(_response);
    });
  }

  protected processGetPlayer(response: Response): Promise<PlayerDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = PlayerDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<PlayerDto>(null as any);
  }

  /**
   * @return OK
   */
  getSelf(): Promise<PlayerDto> {
    let url_ = this.baseUrl + "/players/me";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetSelf(_response);
    });
  }

  protected processGetSelf(response: Response): Promise<PlayerDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = PlayerDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<PlayerDto>(null as any);
  }

  /**
   * @return OK
   */
  gamba(lootBoxId: number): Promise<LootBoxResultDto> {
    let url_ = this.baseUrl + "/players/me/lootboxes/{lootBoxId}/open";
    if (lootBoxId === undefined || lootBoxId === null) {
      throw new globalThis.Error("The parameter 'lootBoxId' must be defined.");
    }
    url_ = url_.replace("{lootBoxId}", encodeURIComponent("" + lootBoxId));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "PUT",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGamba(_response);
    });
  }

  protected processGamba(response: Response): Promise<LootBoxResultDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = LootBoxResultDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<LootBoxResultDto>(null as any);
  }

  /**
   * @return OK
   */
  getLoginUrl(): Promise<string> {
    let url_ = this.baseUrl + "/sessions/login";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processGetLoginUrl(_response);
    });
  }

  protected processGetLoginUrl(response: Response): Promise<string> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = resultData200 !== undefined ? resultData200 : null as any;

        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<string>(null as any);
  }

  /**
   * @param code (optional)
   * @param state (optional)
   * @return OK
   */
  twitchCallback(
    code?: string | undefined,
    state?: string | undefined,
  ): Promise<TokenDto> {
    let url_ = this.baseUrl + "/sessions/twitch/callback?";
    if (code === null) {
      throw new globalThis.Error("The parameter 'code' cannot be null.");
    } else if (code !== undefined) {
      url_ += "code=" + encodeURIComponent("" + code) + "&";
    }
    if (state === null) {
      throw new globalThis.Error("The parameter 'state' cannot be null.");
    } else if (state !== undefined) {
      url_ += "state=" + encodeURIComponent("" + state) + "&";
    }
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processTwitchCallback(_response);
    });
  }

  protected processTwitchCallback(response: Response): Promise<TokenDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = TokenDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<TokenDto>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  placeOrder(body?: CreateTransactionDto | undefined): Promise<ModelId> {
    let url_ = this.baseUrl + "/transactions";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processPlaceOrder(_response);
    });
  }

  protected processPlaceOrder(response: Response): Promise<ModelId> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) =>
        _headers[k] = v
      );
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 = _responseText === ""
          ? null
          : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = ModelId.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<ModelId>(null as any);
  }
}

export class CreateTransactionDto implements ICreateTransactionDto {
  creator!: string;
  action!: TransactionAction;
  amount!: number;

  constructor(data?: ICreateTransactionDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.creator = _data["creator"] !== undefined
        ? _data["creator"]
        : null as any;
      this.action = _data["action"] !== undefined
        ? _data["action"]
        : null as any;
      this.amount = _data["amount"] !== undefined
        ? _data["amount"]
        : null as any;
    }
  }

  static fromJS(data: any): CreateTransactionDto {
    data = typeof data === "object" ? data : {};
    let result = new CreateTransactionDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["creator"] = this.creator !== undefined ? this.creator : null as any;
    data["action"] = this.action !== undefined ? this.action : null as any;
    data["amount"] = this.amount !== undefined ? this.amount : null as any;
    return data;
  }
}

export interface ICreateTransactionDto {
  creator: string;
  action: TransactionAction;
  amount: number;
}

export class CreatorDto implements ICreatorDto {
  id!: number;
  created_at!: Date;
  updated_at!: Date;
  name!: string;
  slug!: string;
  platform_id!: string;
  platform!: Platform;
  readonly platform_url!: string;
  avatar_url!: string;
  ticker!: string;
  value!: number;
  stream_status!: StreamStatusDto;
  history!: VoteDto[];
  transactions!: CreatorTransactionDto[];
  shares!: CreatorShareDto[];

  constructor(data?: ICreatorDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.stream_status = new StreamStatusDto();
      this.history = [];
      this.transactions = [];
      this.shares = [];
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"] !== undefined ? _data["id"] : null as any;
      this.created_at = _data["created_at"]
        ? new Date(_data["created_at"].toString())
        : null as any;
      this.updated_at = _data["updated_at"]
        ? new Date(_data["updated_at"].toString())
        : null as any;
      this.name = _data["name"] !== undefined ? _data["name"] : null as any;
      this.slug = _data["slug"] !== undefined ? _data["slug"] : null as any;
      this.platform_id = _data["platform_id"] !== undefined
        ? _data["platform_id"]
        : null as any;
      this.platform = _data["platform"] !== undefined
        ? _data["platform"]
        : null as any;
      (this as any).platform_url = _data["platform_url"] !== undefined
        ? _data["platform_url"]
        : null as any;
      this.avatar_url = _data["avatar_url"] !== undefined
        ? _data["avatar_url"]
        : null as any;
      this.ticker = _data["ticker"] !== undefined
        ? _data["ticker"]
        : null as any;
      this.value = _data["value"] !== undefined ? _data["value"] : null as any;
      this.stream_status = _data["stream_status"]
        ? StreamStatusDto.fromJS(_data["stream_status"])
        : new StreamStatusDto();
      if (Array.isArray(_data["history"])) {
        this.history = [] as any;
        for (let item of _data["history"]) {
          this.history!.push(VoteDto.fromJS(item));
        }
      } else {
        this.history = null as any;
      }
      if (Array.isArray(_data["transactions"])) {
        this.transactions = [] as any;
        for (let item of _data["transactions"]) {
          this.transactions!.push(CreatorTransactionDto.fromJS(item));
        }
      } else {
        this.transactions = null as any;
      }
      if (Array.isArray(_data["shares"])) {
        this.shares = [] as any;
        for (let item of _data["shares"]) {
          this.shares!.push(CreatorShareDto.fromJS(item));
        }
      } else {
        this.shares = null as any;
      }
    }
  }

  static fromJS(data: any): CreatorDto {
    data = typeof data === "object" ? data : {};
    let result = new CreatorDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id !== undefined ? this.id : null as any;
    data["created_at"] = this.created_at
      ? this.created_at.toISOString()
      : null as any;
    data["updated_at"] = this.updated_at
      ? this.updated_at.toISOString()
      : null as any;
    data["name"] = this.name !== undefined ? this.name : null as any;
    data["slug"] = this.slug !== undefined ? this.slug : null as any;
    data["platform_id"] = this.platform_id !== undefined
      ? this.platform_id
      : null as any;
    data["platform"] = this.platform !== undefined
      ? this.platform
      : null as any;
    data["platform_url"] = this.platform_url !== undefined
      ? this.platform_url
      : null as any;
    data["avatar_url"] = this.avatar_url !== undefined
      ? this.avatar_url
      : null as any;
    data["ticker"] = this.ticker !== undefined ? this.ticker : null as any;
    data["value"] = this.value !== undefined ? this.value : null as any;
    data["stream_status"] = this.stream_status
      ? this.stream_status.toJSON()
      : null as any;
    if (Array.isArray(this.history)) {
      data["history"] = [];
      for (let item of this.history) {
        data["history"].push(item ? item.toJSON() : null as any);
      }
    }
    if (Array.isArray(this.transactions)) {
      data["transactions"] = [];
      for (let item of this.transactions) {
        data["transactions"].push(item ? item.toJSON() : null as any);
      }
    }
    if (Array.isArray(this.shares)) {
      data["shares"] = [];
      for (let item of this.shares) {
        data["shares"].push(item ? item.toJSON() : null as any);
      }
    }
    return data;
  }
}

export interface ICreatorDto {
  id: number;
  created_at: Date;
  updated_at: Date;
  name: string;
  slug: string;
  platform_id: string;
  platform: Platform;
  platform_url: string;
  avatar_url: string;
  ticker: string;
  value: number;
  stream_status: StreamStatusDto;
  history: VoteDto[];
  transactions: CreatorTransactionDto[];
  shares: CreatorShareDto[];
}

export class CreatorDtoPaginationDto implements ICreatorDtoPaginationDto {
  data!: CreatorDto[];
  total!: number;

  constructor(data?: ICreatorDtoPaginationDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.data = [];
    }
  }

  init(_data?: any) {
    if (_data) {
      if (Array.isArray(_data["data"])) {
        this.data = [] as any;
        for (let item of _data["data"]) {
          this.data!.push(CreatorDto.fromJS(item));
        }
      } else {
        this.data = null as any;
      }
      this.total = _data["total"] !== undefined ? _data["total"] : null as any;
    }
  }

  static fromJS(data: any): CreatorDtoPaginationDto {
    data = typeof data === "object" ? data : {};
    let result = new CreatorDtoPaginationDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    if (Array.isArray(this.data)) {
      data["data"] = [];
      for (let item of this.data) {
        data["data"].push(item ? item.toJSON() : null as any);
      }
    }
    data["total"] = this.total !== undefined ? this.total : null as any;
    return data;
  }
}

export interface ICreatorDtoPaginationDto {
  data: CreatorDto[];
  total: number;
}

export class CreatorOptOutDto implements ICreatorOptOutDto {
  id!: number;
  created_at!: Date;
  updated_at!: Date;
  platform_id!: string;
  platform!: Platform;

  constructor(data?: ICreatorOptOutDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"] !== undefined ? _data["id"] : null as any;
      this.created_at = _data["created_at"]
        ? new Date(_data["created_at"].toString())
        : null as any;
      this.updated_at = _data["updated_at"]
        ? new Date(_data["updated_at"].toString())
        : null as any;
      this.platform_id = _data["platform_id"] !== undefined
        ? _data["platform_id"]
        : null as any;
      this.platform = _data["platform"] !== undefined
        ? _data["platform"]
        : null as any;
    }
  }

  static fromJS(data: any): CreatorOptOutDto {
    data = typeof data === "object" ? data : {};
    let result = new CreatorOptOutDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id !== undefined ? this.id : null as any;
    data["created_at"] = this.created_at
      ? this.created_at.toISOString()
      : null as any;
    data["updated_at"] = this.updated_at
      ? this.updated_at.toISOString()
      : null as any;
    data["platform_id"] = this.platform_id !== undefined
      ? this.platform_id
      : null as any;
    data["platform"] = this.platform !== undefined
      ? this.platform
      : null as any;
    return data;
  }
}

export interface ICreatorOptOutDto {
  id: number;
  created_at: Date;
  updated_at: Date;
  platform_id: string;
  platform: Platform;
}

export enum CreatorOrderBy {
  Name = "Name",
  Value = "Value",
  IsLive = "IsLive",
}

export class CreatorPartialDto implements ICreatorPartialDto {
  id!: number;
  created_at!: Date;
  updated_at!: Date;
  name!: string;
  slug!: string;
  platform_id!: string;
  platform!: Platform;
  readonly platform_url!: string;
  avatar_url!: string;
  ticker!: string;
  value!: number;
  stream_status!: StreamStatusDto;
  history!: VoteDto[];

  constructor(data?: ICreatorPartialDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.stream_status = new StreamStatusDto();
      this.history = [];
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"] !== undefined ? _data["id"] : null as any;
      this.created_at = _data["created_at"]
        ? new Date(_data["created_at"].toString())
        : null as any;
      this.updated_at = _data["updated_at"]
        ? new Date(_data["updated_at"].toString())
        : null as any;
      this.name = _data["name"] !== undefined ? _data["name"] : null as any;
      this.slug = _data["slug"] !== undefined ? _data["slug"] : null as any;
      this.platform_id = _data["platform_id"] !== undefined
        ? _data["platform_id"]
        : null as any;
      this.platform = _data["platform"] !== undefined
        ? _data["platform"]
        : null as any;
      (this as any).platform_url = _data["platform_url"] !== undefined
        ? _data["platform_url"]
        : null as any;
      this.avatar_url = _data["avatar_url"] !== undefined
        ? _data["avatar_url"]
        : null as any;
      this.ticker = _data["ticker"] !== undefined
        ? _data["ticker"]
        : null as any;
      this.value = _data["value"] !== undefined ? _data["value"] : null as any;
      this.stream_status = _data["stream_status"]
        ? StreamStatusDto.fromJS(_data["stream_status"])
        : new StreamStatusDto();
      if (Array.isArray(_data["history"])) {
        this.history = [] as any;
        for (let item of _data["history"]) {
          this.history!.push(VoteDto.fromJS(item));
        }
      } else {
        this.history = null as any;
      }
    }
  }

  static fromJS(data: any): CreatorPartialDto {
    data = typeof data === "object" ? data : {};
    let result = new CreatorPartialDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id !== undefined ? this.id : null as any;
    data["created_at"] = this.created_at
      ? this.created_at.toISOString()
      : null as any;
    data["updated_at"] = this.updated_at
      ? this.updated_at.toISOString()
      : null as any;
    data["name"] = this.name !== undefined ? this.name : null as any;
    data["slug"] = this.slug !== undefined ? this.slug : null as any;
    data["platform_id"] = this.platform_id !== undefined
      ? this.platform_id
      : null as any;
    data["platform"] = this.platform !== undefined
      ? this.platform
      : null as any;
    data["platform_url"] = this.platform_url !== undefined
      ? this.platform_url
      : null as any;
    data["avatar_url"] = this.avatar_url !== undefined
      ? this.avatar_url
      : null as any;
    data["ticker"] = this.ticker !== undefined ? this.ticker : null as any;
    data["value"] = this.value !== undefined ? this.value : null as any;
    data["stream_status"] = this.stream_status
      ? this.stream_status.toJSON()
      : null as any;
    if (Array.isArray(this.history)) {
      data["history"] = [];
      for (let item of this.history) {
        data["history"].push(item ? item.toJSON() : null as any);
      }
    }
    return data;
  }
}

export interface ICreatorPartialDto {
  id: number;
  created_at: Date;
  updated_at: Date;
  name: string;
  slug: string;
  platform_id: string;
  platform: Platform;
  platform_url: string;
  avatar_url: string;
  ticker: string;
  value: number;
  stream_status: StreamStatusDto;
  history: VoteDto[];
}

export class CreatorRarityDto implements ICreatorRarityDto {
  creator!: CreatorPartialDto;
  rarity!: Rarity;

  constructor(data?: ICreatorRarityDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.creator = new CreatorPartialDto();
    }
  }

  init(_data?: any) {
    if (_data) {
      this.creator = _data["creator"]
        ? CreatorPartialDto.fromJS(_data["creator"])
        : new CreatorPartialDto();
      this.rarity = _data["rarity"] !== undefined
        ? _data["rarity"]
        : null as any;
    }
  }

  static fromJS(data: any): CreatorRarityDto {
    data = typeof data === "object" ? data : {};
    let result = new CreatorRarityDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["creator"] = this.creator ? this.creator.toJSON() : null as any;
    data["rarity"] = this.rarity !== undefined ? this.rarity : null as any;
    return data;
  }
}

export interface ICreatorRarityDto {
  creator: CreatorPartialDto;
  rarity: Rarity;
}

export class CreatorShareDto implements ICreatorShareDto {
  player!: PlayerPartialDto;
  quantity!: number;

  constructor(data?: ICreatorShareDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.player = new PlayerPartialDto();
    }
  }

  init(_data?: any) {
    if (_data) {
      this.player = _data["player"]
        ? PlayerPartialDto.fromJS(_data["player"])
        : new PlayerPartialDto();
      this.quantity = _data["quantity"] !== undefined
        ? _data["quantity"]
        : null as any;
    }
  }

  static fromJS(data: any): CreatorShareDto {
    data = typeof data === "object" ? data : {};
    let result = new CreatorShareDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["player"] = this.player ? this.player.toJSON() : null as any;
    data["quantity"] = this.quantity !== undefined
      ? this.quantity
      : null as any;
    return data;
  }
}

export interface ICreatorShareDto {
  player: PlayerPartialDto;
  quantity: number;
}

export class CreatorTransactionDto implements ICreatorTransactionDto {
  id!: number;
  created_at!: Date;
  updated_at!: Date;
  quantity!: number;
  value!: number;
  action!: TransactionAction;
  creator_id!: number;
  player_id!: number;
  player!: PlayerPartialDto;

  constructor(data?: ICreatorTransactionDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.player = new PlayerPartialDto();
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"] !== undefined ? _data["id"] : null as any;
      this.created_at = _data["created_at"]
        ? new Date(_data["created_at"].toString())
        : null as any;
      this.updated_at = _data["updated_at"]
        ? new Date(_data["updated_at"].toString())
        : null as any;
      this.quantity = _data["quantity"] !== undefined
        ? _data["quantity"]
        : null as any;
      this.value = _data["value"] !== undefined ? _data["value"] : null as any;
      this.action = _data["action"] !== undefined
        ? _data["action"]
        : null as any;
      this.creator_id = _data["creator_id"] !== undefined
        ? _data["creator_id"]
        : null as any;
      this.player_id = _data["player_id"] !== undefined
        ? _data["player_id"]
        : null as any;
      this.player = _data["player"]
        ? PlayerPartialDto.fromJS(_data["player"])
        : new PlayerPartialDto();
    }
  }

  static fromJS(data: any): CreatorTransactionDto {
    data = typeof data === "object" ? data : {};
    let result = new CreatorTransactionDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id !== undefined ? this.id : null as any;
    data["created_at"] = this.created_at
      ? this.created_at.toISOString()
      : null as any;
    data["updated_at"] = this.updated_at
      ? this.updated_at.toISOString()
      : null as any;
    data["quantity"] = this.quantity !== undefined
      ? this.quantity
      : null as any;
    data["value"] = this.value !== undefined ? this.value : null as any;
    data["action"] = this.action !== undefined ? this.action : null as any;
    data["creator_id"] = this.creator_id !== undefined
      ? this.creator_id
      : null as any;
    data["player_id"] = this.player_id !== undefined
      ? this.player_id
      : null as any;
    data["player"] = this.player ? this.player.toJSON() : null as any;
    return data;
  }
}

export interface ICreatorTransactionDto {
  id: number;
  created_at: Date;
  updated_at: Date;
  quantity: number;
  value: number;
  action: TransactionAction;
  creator_id: number;
  player_id: number;
  player: PlayerPartialDto;
}

export class LootBoxDto implements ILootBoxDto {
  id!: number;
  created_at!: Date;
  updated_at!: Date;
  is_open!: boolean;
  result!: CreatorPartialDto;
  player!: PlayerPartialDto;

  constructor(data?: ILootBoxDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.result = new CreatorPartialDto();
      this.player = new PlayerPartialDto();
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"] !== undefined ? _data["id"] : null as any;
      this.created_at = _data["created_at"]
        ? new Date(_data["created_at"].toString())
        : null as any;
      this.updated_at = _data["updated_at"]
        ? new Date(_data["updated_at"].toString())
        : null as any;
      this.is_open = _data["is_open"] !== undefined
        ? _data["is_open"]
        : null as any;
      this.result = _data["result"]
        ? CreatorPartialDto.fromJS(_data["result"])
        : new CreatorPartialDto();
      this.player = _data["player"]
        ? PlayerPartialDto.fromJS(_data["player"])
        : new PlayerPartialDto();
    }
  }

  static fromJS(data: any): LootBoxDto {
    data = typeof data === "object" ? data : {};
    let result = new LootBoxDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id !== undefined ? this.id : null as any;
    data["created_at"] = this.created_at
      ? this.created_at.toISOString()
      : null as any;
    data["updated_at"] = this.updated_at
      ? this.updated_at.toISOString()
      : null as any;
    data["is_open"] = this.is_open !== undefined ? this.is_open : null as any;
    data["result"] = this.result ? this.result.toJSON() : null as any;
    data["player"] = this.player ? this.player.toJSON() : null as any;
    return data;
  }
}

export interface ILootBoxDto {
  id: number;
  created_at: Date;
  updated_at: Date;
  is_open: boolean;
  result: CreatorPartialDto;
  player: PlayerPartialDto;
}

export class LootBoxResultDto implements ILootBoxResultDto {
  lootbox_id!: ModelId;
  player!: PlayerPartialDto;
  result!: CreatorRarityDto;
  transaction_id!: ModelId;
  rarities!: CreatorRarityDto[];

  constructor(data?: ILootBoxResultDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.lootbox_id = new ModelId();
      this.player = new PlayerPartialDto();
      this.result = new CreatorRarityDto();
      this.transaction_id = new ModelId();
      this.rarities = [];
    }
  }

  init(_data?: any) {
    if (_data) {
      this.lootbox_id = _data["lootbox_id"]
        ? ModelId.fromJS(_data["lootbox_id"])
        : new ModelId();
      this.player = _data["player"]
        ? PlayerPartialDto.fromJS(_data["player"])
        : new PlayerPartialDto();
      this.result = _data["result"]
        ? CreatorRarityDto.fromJS(_data["result"])
        : new CreatorRarityDto();
      this.transaction_id = _data["transaction_id"]
        ? ModelId.fromJS(_data["transaction_id"])
        : new ModelId();
      if (Array.isArray(_data["rarities"])) {
        this.rarities = [] as any;
        for (let item of _data["rarities"]) {
          this.rarities!.push(CreatorRarityDto.fromJS(item));
        }
      } else {
        this.rarities = null as any;
      }
    }
  }

  static fromJS(data: any): LootBoxResultDto {
    data = typeof data === "object" ? data : {};
    let result = new LootBoxResultDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["lootbox_id"] = this.lootbox_id
      ? this.lootbox_id.toJSON()
      : null as any;
    data["player"] = this.player ? this.player.toJSON() : null as any;
    data["result"] = this.result ? this.result.toJSON() : null as any;
    data["transaction_id"] = this.transaction_id
      ? this.transaction_id.toJSON()
      : null as any;
    if (Array.isArray(this.rarities)) {
      data["rarities"] = [];
      for (let item of this.rarities) {
        data["rarities"].push(item ? item.toJSON() : null as any);
      }
    }
    return data;
  }
}

export interface ILootBoxResultDto {
  lootbox_id: ModelId;
  player: PlayerPartialDto;
  result: CreatorRarityDto;
  transaction_id: ModelId;
  rarities: CreatorRarityDto[];
}

export class ModelId implements IModelId {
  value!: number;

  constructor(data?: IModelId) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.value = _data["value"] !== undefined ? _data["value"] : null as any;
    }
  }

  static fromJS(data: any): ModelId {
    data = typeof data === "object" ? data : {};
    let result = new ModelId();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["value"] = this.value !== undefined ? this.value : null as any;
    return data;
  }
}

export interface IModelId {
  value: number;
}

export enum OrderDirection {
  Ascending = "Ascending",
  Descending = "Descending",
}

export enum Platform {
  Twitch = "Twitch",
}

export class PlayerDto implements IPlayerDto {
  id!: number;
  created_at!: Date;
  updated_at!: Date;
  name!: string;
  slug!: string;
  platform_id!: string;
  platform!: Platform;
  readonly platform_url!: string;
  avatar_url!: string;
  credits!: number;
  portfolio!: number;
  value!: number;
  type!: PlayerType;
  transactions!: PlayerTransactionDto[];
  loot_boxes!: LootBoxDto[];
  shares!: PlayerShareDto[];
  history!: PortfolioSnapshotDto[];

  constructor(data?: IPlayerDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.transactions = [];
      this.loot_boxes = [];
      this.shares = [];
      this.history = [];
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"] !== undefined ? _data["id"] : null as any;
      this.created_at = _data["created_at"]
        ? new Date(_data["created_at"].toString())
        : null as any;
      this.updated_at = _data["updated_at"]
        ? new Date(_data["updated_at"].toString())
        : null as any;
      this.name = _data["name"] !== undefined ? _data["name"] : null as any;
      this.slug = _data["slug"] !== undefined ? _data["slug"] : null as any;
      this.platform_id = _data["platform_id"] !== undefined
        ? _data["platform_id"]
        : null as any;
      this.platform = _data["platform"] !== undefined
        ? _data["platform"]
        : null as any;
      (this as any).platform_url = _data["platform_url"] !== undefined
        ? _data["platform_url"]
        : null as any;
      this.avatar_url = _data["avatar_url"] !== undefined
        ? _data["avatar_url"]
        : null as any;
      this.credits = _data["credits"] !== undefined
        ? _data["credits"]
        : null as any;
      this.portfolio = _data["portfolio"] !== undefined
        ? _data["portfolio"]
        : null as any;
      this.value = _data["value"] !== undefined ? _data["value"] : null as any;
      this.type = _data["type"] !== undefined ? _data["type"] : null as any;
      if (Array.isArray(_data["transactions"])) {
        this.transactions = [] as any;
        for (let item of _data["transactions"]) {
          this.transactions!.push(PlayerTransactionDto.fromJS(item));
        }
      } else {
        this.transactions = null as any;
      }
      if (Array.isArray(_data["loot_boxes"])) {
        this.loot_boxes = [] as any;
        for (let item of _data["loot_boxes"]) {
          this.loot_boxes!.push(LootBoxDto.fromJS(item));
        }
      } else {
        this.loot_boxes = null as any;
      }
      if (Array.isArray(_data["shares"])) {
        this.shares = [] as any;
        for (let item of _data["shares"]) {
          this.shares!.push(PlayerShareDto.fromJS(item));
        }
      } else {
        this.shares = null as any;
      }
      if (Array.isArray(_data["history"])) {
        this.history = [] as any;
        for (let item of _data["history"]) {
          this.history!.push(PortfolioSnapshotDto.fromJS(item));
        }
      } else {
        this.history = null as any;
      }
    }
  }

  static fromJS(data: any): PlayerDto {
    data = typeof data === "object" ? data : {};
    let result = new PlayerDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id !== undefined ? this.id : null as any;
    data["created_at"] = this.created_at
      ? this.created_at.toISOString()
      : null as any;
    data["updated_at"] = this.updated_at
      ? this.updated_at.toISOString()
      : null as any;
    data["name"] = this.name !== undefined ? this.name : null as any;
    data["slug"] = this.slug !== undefined ? this.slug : null as any;
    data["platform_id"] = this.platform_id !== undefined
      ? this.platform_id
      : null as any;
    data["platform"] = this.platform !== undefined
      ? this.platform
      : null as any;
    data["platform_url"] = this.platform_url !== undefined
      ? this.platform_url
      : null as any;
    data["avatar_url"] = this.avatar_url !== undefined
      ? this.avatar_url
      : null as any;
    data["credits"] = this.credits !== undefined ? this.credits : null as any;
    data["portfolio"] = this.portfolio !== undefined
      ? this.portfolio
      : null as any;
    data["value"] = this.value !== undefined ? this.value : null as any;
    data["type"] = this.type !== undefined ? this.type : null as any;
    if (Array.isArray(this.transactions)) {
      data["transactions"] = [];
      for (let item of this.transactions) {
        data["transactions"].push(item ? item.toJSON() : null as any);
      }
    }
    if (Array.isArray(this.loot_boxes)) {
      data["loot_boxes"] = [];
      for (let item of this.loot_boxes) {
        data["loot_boxes"].push(item ? item.toJSON() : null as any);
      }
    }
    if (Array.isArray(this.shares)) {
      data["shares"] = [];
      for (let item of this.shares) {
        data["shares"].push(item ? item.toJSON() : null as any);
      }
    }
    if (Array.isArray(this.history)) {
      data["history"] = [];
      for (let item of this.history) {
        data["history"].push(item ? item.toJSON() : null as any);
      }
    }
    return data;
  }
}

export interface IPlayerDto {
  id: number;
  created_at: Date;
  updated_at: Date;
  name: string;
  slug: string;
  platform_id: string;
  platform: Platform;
  platform_url: string;
  avatar_url: string;
  credits: number;
  portfolio: number;
  value: number;
  type: PlayerType;
  transactions: PlayerTransactionDto[];
  loot_boxes: LootBoxDto[];
  shares: PlayerShareDto[];
  history: PortfolioSnapshotDto[];
}

export class PlayerDtoPaginationDto implements IPlayerDtoPaginationDto {
  data!: PlayerDto[];
  total!: number;

  constructor(data?: IPlayerDtoPaginationDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.data = [];
    }
  }

  init(_data?: any) {
    if (_data) {
      if (Array.isArray(_data["data"])) {
        this.data = [] as any;
        for (let item of _data["data"]) {
          this.data!.push(PlayerDto.fromJS(item));
        }
      } else {
        this.data = null as any;
      }
      this.total = _data["total"] !== undefined ? _data["total"] : null as any;
    }
  }

  static fromJS(data: any): PlayerDtoPaginationDto {
    data = typeof data === "object" ? data : {};
    let result = new PlayerDtoPaginationDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    if (Array.isArray(this.data)) {
      data["data"] = [];
      for (let item of this.data) {
        data["data"].push(item ? item.toJSON() : null as any);
      }
    }
    data["total"] = this.total !== undefined ? this.total : null as any;
    return data;
  }
}

export interface IPlayerDtoPaginationDto {
  data: PlayerDto[];
  total: number;
}

export enum PlayerOrderBy {
  Name = "Name",
  Credits = "Credits",
  Portfolio = "Portfolio",
}

export class PlayerPartialDto implements IPlayerPartialDto {
  id!: number;
  created_at!: Date;
  updated_at!: Date;
  name!: string;
  slug!: string;
  platform_id!: string;
  platform!: Platform;
  readonly platform_url!: string;
  avatar_url!: string;
  credits!: number;
  portfolio!: number;
  value!: number;
  type!: PlayerType;

  constructor(data?: IPlayerPartialDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"] !== undefined ? _data["id"] : null as any;
      this.created_at = _data["created_at"]
        ? new Date(_data["created_at"].toString())
        : null as any;
      this.updated_at = _data["updated_at"]
        ? new Date(_data["updated_at"].toString())
        : null as any;
      this.name = _data["name"] !== undefined ? _data["name"] : null as any;
      this.slug = _data["slug"] !== undefined ? _data["slug"] : null as any;
      this.platform_id = _data["platform_id"] !== undefined
        ? _data["platform_id"]
        : null as any;
      this.platform = _data["platform"] !== undefined
        ? _data["platform"]
        : null as any;
      (this as any).platform_url = _data["platform_url"] !== undefined
        ? _data["platform_url"]
        : null as any;
      this.avatar_url = _data["avatar_url"] !== undefined
        ? _data["avatar_url"]
        : null as any;
      this.credits = _data["credits"] !== undefined
        ? _data["credits"]
        : null as any;
      this.portfolio = _data["portfolio"] !== undefined
        ? _data["portfolio"]
        : null as any;
      this.value = _data["value"] !== undefined ? _data["value"] : null as any;
      this.type = _data["type"] !== undefined ? _data["type"] : null as any;
    }
  }

  static fromJS(data: any): PlayerPartialDto {
    data = typeof data === "object" ? data : {};
    let result = new PlayerPartialDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id !== undefined ? this.id : null as any;
    data["created_at"] = this.created_at
      ? this.created_at.toISOString()
      : null as any;
    data["updated_at"] = this.updated_at
      ? this.updated_at.toISOString()
      : null as any;
    data["name"] = this.name !== undefined ? this.name : null as any;
    data["slug"] = this.slug !== undefined ? this.slug : null as any;
    data["platform_id"] = this.platform_id !== undefined
      ? this.platform_id
      : null as any;
    data["platform"] = this.platform !== undefined
      ? this.platform
      : null as any;
    data["platform_url"] = this.platform_url !== undefined
      ? this.platform_url
      : null as any;
    data["avatar_url"] = this.avatar_url !== undefined
      ? this.avatar_url
      : null as any;
    data["credits"] = this.credits !== undefined ? this.credits : null as any;
    data["portfolio"] = this.portfolio !== undefined
      ? this.portfolio
      : null as any;
    data["value"] = this.value !== undefined ? this.value : null as any;
    data["type"] = this.type !== undefined ? this.type : null as any;
    return data;
  }
}

export interface IPlayerPartialDto {
  id: number;
  created_at: Date;
  updated_at: Date;
  name: string;
  slug: string;
  platform_id: string;
  platform: Platform;
  platform_url: string;
  avatar_url: string;
  credits: number;
  portfolio: number;
  value: number;
  type: PlayerType;
}

export class PlayerShareDto implements IPlayerShareDto {
  creator!: CreatorPartialDto;
  quantity!: number;

  constructor(data?: IPlayerShareDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.creator = new CreatorPartialDto();
    }
  }

  init(_data?: any) {
    if (_data) {
      this.creator = _data["creator"]
        ? CreatorPartialDto.fromJS(_data["creator"])
        : new CreatorPartialDto();
      this.quantity = _data["quantity"] !== undefined
        ? _data["quantity"]
        : null as any;
    }
  }

  static fromJS(data: any): PlayerShareDto {
    data = typeof data === "object" ? data : {};
    let result = new PlayerShareDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["creator"] = this.creator ? this.creator.toJSON() : null as any;
    data["quantity"] = this.quantity !== undefined
      ? this.quantity
      : null as any;
    return data;
  }
}

export interface IPlayerShareDto {
  creator: CreatorPartialDto;
  quantity: number;
}

export class PlayerTransactionDto implements IPlayerTransactionDto {
  id!: number;
  created_at!: Date;
  updated_at!: Date;
  quantity!: number;
  value!: number;
  action!: TransactionAction;
  creator_id!: number;
  player_id!: number;
  creator!: CreatorPartialDto;

  constructor(data?: IPlayerTransactionDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
    if (!data) {
      this.creator = new CreatorPartialDto();
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"] !== undefined ? _data["id"] : null as any;
      this.created_at = _data["created_at"]
        ? new Date(_data["created_at"].toString())
        : null as any;
      this.updated_at = _data["updated_at"]
        ? new Date(_data["updated_at"].toString())
        : null as any;
      this.quantity = _data["quantity"] !== undefined
        ? _data["quantity"]
        : null as any;
      this.value = _data["value"] !== undefined ? _data["value"] : null as any;
      this.action = _data["action"] !== undefined
        ? _data["action"]
        : null as any;
      this.creator_id = _data["creator_id"] !== undefined
        ? _data["creator_id"]
        : null as any;
      this.player_id = _data["player_id"] !== undefined
        ? _data["player_id"]
        : null as any;
      this.creator = _data["creator"]
        ? CreatorPartialDto.fromJS(_data["creator"])
        : new CreatorPartialDto();
    }
  }

  static fromJS(data: any): PlayerTransactionDto {
    data = typeof data === "object" ? data : {};
    let result = new PlayerTransactionDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id !== undefined ? this.id : null as any;
    data["created_at"] = this.created_at
      ? this.created_at.toISOString()
      : null as any;
    data["updated_at"] = this.updated_at
      ? this.updated_at.toISOString()
      : null as any;
    data["quantity"] = this.quantity !== undefined
      ? this.quantity
      : null as any;
    data["value"] = this.value !== undefined ? this.value : null as any;
    data["action"] = this.action !== undefined ? this.action : null as any;
    data["creator_id"] = this.creator_id !== undefined
      ? this.creator_id
      : null as any;
    data["player_id"] = this.player_id !== undefined
      ? this.player_id
      : null as any;
    data["creator"] = this.creator ? this.creator.toJSON() : null as any;
    return data;
  }
}

export interface IPlayerTransactionDto {
  id: number;
  created_at: Date;
  updated_at: Date;
  quantity: number;
  value: number;
  action: TransactionAction;
  creator_id: number;
  player_id: number;
  creator: CreatorPartialDto;
}

export enum PlayerType {
  User = "User",
  Admin = "Admin",
}

export class PortfolioSnapshotDto implements IPortfolioSnapshotDto {
  player_id!: number;
  value!: number;
  time!: Date;

  constructor(data?: IPortfolioSnapshotDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.player_id = _data["player_id"] !== undefined
        ? _data["player_id"]
        : null as any;
      this.value = _data["value"] !== undefined ? _data["value"] : null as any;
      this.time = _data["time"]
        ? new Date(_data["time"].toString())
        : null as any;
    }
  }

  static fromJS(data: any): PortfolioSnapshotDto {
    data = typeof data === "object" ? data : {};
    let result = new PortfolioSnapshotDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["player_id"] = this.player_id !== undefined
      ? this.player_id
      : null as any;
    data["value"] = this.value !== undefined ? this.value : null as any;
    data["time"] = this.time ? this.time.toISOString() : null as any;
    return data;
  }
}

export interface IPortfolioSnapshotDto {
  player_id: number;
  value: number;
  time: Date;
}

export enum Rarity {
  Pennies = "Pennies",
  Common = "Common",
  Rare = "Rare",
  Epic = "Epic",
}

export class StreamStatusDto implements IStreamStatusDto {
  is_live!: boolean;
  started_at?: Date | null;
  ended_at?: Date | null;

  constructor(data?: IStreamStatusDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.is_live = _data["is_live"] !== undefined
        ? _data["is_live"]
        : null as any;
      this.started_at = _data["started_at"]
        ? new Date(_data["started_at"].toString())
        : null as any;
      this.ended_at = _data["ended_at"]
        ? new Date(_data["ended_at"].toString())
        : null as any;
    }
  }

  static fromJS(data: any): StreamStatusDto {
    data = typeof data === "object" ? data : {};
    let result = new StreamStatusDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["is_live"] = this.is_live !== undefined ? this.is_live : null as any;
    data["started_at"] = this.started_at
      ? this.started_at.toISOString()
      : null as any;
    data["ended_at"] = this.ended_at
      ? this.ended_at.toISOString()
      : null as any;
    return data;
  }
}

export interface IStreamStatusDto {
  is_live: boolean;
  started_at?: Date | null;
  ended_at?: Date | null;
}

export class TokenDto implements ITokenDto {
  access_token!: string;

  constructor(data?: ITokenDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.access_token = _data["access_token"] !== undefined
        ? _data["access_token"]
        : null as any;
    }
  }

  static fromJS(data: any): TokenDto {
    data = typeof data === "object" ? data : {};
    let result = new TokenDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["access_token"] = this.access_token !== undefined
      ? this.access_token
      : null as any;
    return data;
  }
}

export interface ITokenDto {
  access_token: string;
}

export enum TransactionAction {
  Buy = "Buy",
  Sell = "Sell",
  Open = "Open",
}

export class VoteDto implements IVoteDto {
  creator_id!: number;
  value!: number;
  time!: Date;

  constructor(data?: IVoteDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) {
          (this as any)[property] = (data as any)[property];
        }
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.creator_id = _data["creator_id"] !== undefined
        ? _data["creator_id"]
        : null as any;
      this.value = _data["value"] !== undefined ? _data["value"] : null as any;
      this.time = _data["time"]
        ? new Date(_data["time"].toString())
        : null as any;
    }
  }

  static fromJS(data: any): VoteDto {
    data = typeof data === "object" ? data : {};
    let result = new VoteDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["creator_id"] = this.creator_id !== undefined
      ? this.creator_id
      : null as any;
    data["value"] = this.value !== undefined ? this.value : null as any;
    data["time"] = this.time ? this.time.toISOString() : null as any;
    return data;
  }
}

export interface IVoteDto {
  creator_id: number;
  value: number;
  time: Date;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) {
    throw result;
  } else {
    throw new ApiException(message, status, response, headers, null);
  }
}
