CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS creators (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker            text             NOT NULL,
    value             double precision NOT NULL,
    stream_is_live    boolean          NOT NULL,
    stream_started_at timestamptz      NOT NULL,
    stream_ended_at   timestamptz      NOT NULL,
    created_at        timestamptz      NOT NULL,
    updated_at        timestamptz      NOT NULL,
    name              text             NOT NULL,
    slug              text             NOT NULL,
    platform_id       text             NOT NULL,
    platform          text             NOT NULL,
    avatar_url        text             NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_creators_slug ON creators (slug);
CREATE UNIQUE INDEX IF NOT EXISTS ix_creators_ticker ON creators (ticker);
CREATE UNIQUE INDEX IF NOT EXISTS ix_creators_platform_platform_id ON creators (platform, platform_id);
CREATE INDEX IF NOT EXISTS ix_creators_name ON creators (name);
CREATE INDEX IF NOT EXISTS ix_creators_name_trgm ON creators USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_creators_value ON creators (value);
CREATE INDEX IF NOT EXISTS ix_creators_live_value ON creators (value) WHERE stream_is_live;

CREATE TABLE IF NOT EXISTS players (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credits     double precision NOT NULL,
    portfolio   double precision NOT NULL,
    type        text             NOT NULL,
    created_at  timestamptz      NOT NULL,
    updated_at  timestamptz      NOT NULL,
    name        text             NOT NULL,
    slug        text             NOT NULL,
    platform_id text             NOT NULL,
    platform    text             NOT NULL,
    avatar_url  text             NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_players_slug ON players (slug);
CREATE UNIQUE INDEX IF NOT EXISTS ix_players_platform_id ON players (platform_id);
CREATE INDEX IF NOT EXISTS ix_players_type ON players (type);
CREATE INDEX IF NOT EXISTS ix_players_name ON players (name);
CREATE INDEX IF NOT EXISTS ix_players_name_trgm ON players USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_players_credits ON players (credits);
CREATE INDEX IF NOT EXISTS ix_players_portfolio ON players (portfolio);

CREATE TABLE IF NOT EXISTS transactions (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   integer          NOT NULL,
    value      double precision NOT NULL,
    action     text             NOT NULL,
    creator_id integer          NOT NULL REFERENCES creators (id) ON DELETE CASCADE,
    player_id  integer          NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    created_at timestamptz      NOT NULL,
    updated_at timestamptz      NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_transactions_creator_created ON transactions (creator_id, created_at);
CREATE INDEX IF NOT EXISTS ix_transactions_player_created ON transactions (player_id, created_at);
DROP INDEX IF EXISTS ix_transactions_creator_id;
DROP INDEX IF EXISTS ix_transactions_player_id;

CREATE TABLE IF NOT EXISTS loot_boxes (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id  integer     NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    result_id  integer         NULL REFERENCES creators (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_loot_boxes_player_id ON loot_boxes (player_id);
CREATE INDEX IF NOT EXISTS ix_loot_boxes_result_id ON loot_boxes (result_id);
CREATE INDEX IF NOT EXISTS ix_loot_boxes_player_unopened ON loot_boxes (player_id) WHERE result_id IS NULL;

CREATE TABLE IF NOT EXISTS votes (
    value      double precision NOT NULL,
    time       timestamptz      NOT NULL,
    creator_id integer          NOT NULL REFERENCES creators (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_votes_creator_id_time ON votes (creator_id, time);

CREATE TABLE IF NOT EXISTS player_portfolios (
    value     double precision NOT NULL,
    player_id integer          NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    time      timestamptz      NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_player_portfolios_player_id_time ON player_portfolios (player_id, time);

CREATE TABLE IF NOT EXISTS creator_applications (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitter_id integer     NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    platform     integer     NOT NULL,
    platform_id  text        NOT NULL,
    ticker       text        NOT NULL,
    name         text        NOT NULL,
    status       text        NOT NULL,
    created_at   timestamptz NOT NULL,
    updated_at   timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_creator_applications_submitter_id ON creator_applications (submitter_id);

CREATE TABLE IF NOT EXISTS creator_opt_outs (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id text        NOT NULL,
    platform    integer     NOT NULL,
    reason      text        NOT NULL,
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_creator_opt_outs_platform_id ON creator_opt_outs (platform_id);
