-- Schema ported from the Entity Framework migrations in
-- `TTX.App/Data/Migrations` (Init + UseDoublesForMoney + Cleanup, squashed).
--
-- Notes on column conventions carried over verbatim so the `sqlx` queries
-- match the original database:
--   * `players`/`creators` store `platform` as TEXT (the enum name).
--   * `creator_opt_outs`/`creator_applications` store `"Platform"` as the raw
--     enum INTEGER, with PascalCase column names (`"Platform"`, `"Reason"`).
--   * money columns are DOUBLE PRECISION.

CREATE TABLE creators (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker            text             NOT NULL,
    value             double precision NOT NULL,
    stream_is_live    boolean          NOT NULL,
    stream_started_at timestamptz      NOT NULL,
    stream_ended_at   timestamptz      NOT NULL,
    created_at        timestamptz      NOT NULL,
    updated_at        timestamptz      NOT NULL,
    name              text             NOT NULL,
    slug              text             NOT NULL,
    platform_id       text             NOT NULL,
    platform          text             NOT NULL,
    avatar_url        text             NOT NULL
);
CREATE UNIQUE INDEX ix_creators_slug ON creators (slug);
CREATE UNIQUE INDEX ix_creators_ticker ON creators (ticker);
CREATE UNIQUE INDEX ix_creators_platform_platform_id ON creators (platform, platform_id);

CREATE TABLE players (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credits     double precision NOT NULL,
    portfolio   double precision NOT NULL,
    type        text             NOT NULL,
    created_at  timestamptz      NOT NULL,
    updated_at  timestamptz      NOT NULL,
    name        text             NOT NULL,
    slug        text             NOT NULL,
    platform_id text             NOT NULL,
    platform    text             NOT NULL,
    avatar_url  text             NOT NULL
);
CREATE UNIQUE INDEX ix_players_slug ON players (slug);
CREATE UNIQUE INDEX ix_players_platform_id ON players (platform_id);
CREATE INDEX ix_players_type ON players (type);

CREATE TABLE transactions (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   integer          NOT NULL,
    value      double precision NOT NULL,
    action     text             NOT NULL,
    creator_id integer          NOT NULL REFERENCES creators (id) ON DELETE CASCADE,
    player_id  integer          NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    created_at timestamptz      NOT NULL,
    updated_at timestamptz      NOT NULL
);
CREATE INDEX ix_transactions_creator_id ON transactions (creator_id);
CREATE INDEX ix_transactions_player_id ON transactions (player_id);

CREATE TABLE loot_boxes (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id  integer     NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    result_id  integer         NULL REFERENCES creators (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
CREATE INDEX ix_loot_boxes_player_id ON loot_boxes (player_id);
CREATE INDEX ix_loot_boxes_result_id ON loot_boxes (result_id);

CREATE TABLE votes (
    value      double precision NOT NULL,
    time       timestamptz      NOT NULL,
    creator_id integer          NOT NULL REFERENCES creators (id) ON DELETE CASCADE
);
CREATE INDEX ix_votes_creator_id_time ON votes (creator_id, time);

CREATE TABLE player_portfolios (
    value     double precision NOT NULL,
    player_id integer          NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    time      timestamptz      NOT NULL
);
CREATE INDEX ix_player_portfolios_player_id_time ON player_portfolios (player_id, time);

CREATE TABLE creator_applications (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitter_id integer     NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    "Platform"   integer     NOT NULL,
    platform_id  text        NOT NULL,
    ticker       text        NOT NULL,
    name         text        NOT NULL,
    status       text        NOT NULL,
    created_at   timestamptz NOT NULL,
    updated_at   timestamptz NOT NULL
);
CREATE INDEX ix_creator_applications_submitter_id ON creator_applications (submitter_id);

CREATE TABLE creator_opt_outs (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id text        NOT NULL,
    "Platform"  integer     NOT NULL,
    "Reason"    text        NOT NULL,
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL
);
CREATE UNIQUE INDEX ix_creator_opt_outs_platform_id ON creator_opt_outs (platform_id);
