services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: timescale/timescaledb:latest-pg17
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  ttx-dataprotection: { }
  pg-data: { }
