{{- if .Values.config.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.name }}
  {{- include "ttx.namespace" . | nindent 2 }}
  labels:
    {{- include "ttx.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.config.stringData | nindent 2 }}
{{- end }}
