---
apiVersion: v1
kind: Secret
metadata:
  name: ttx-config
  namespace: ttx
type: Opaque
stringData:
  TTX_ConnectionString: ""
  TTX_Redis__Host: ""
  TTX_ValueMonitor__Buffer: "15"
  TTX_ValueMonitor__Redis__Database: "0"
  TTX_Reports__Cooldown: "30"
  TTX_Api__Redis__Database: "1"
  TTX_Api__Twitch__ClientId: ""
  TTX_Api__Twitch__ClientSecret: ""
  TTX_Api__Twitch__RedirectUri: ""
  TTX_Reports__Discord__WebhookUrl: ""

---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ttx-regcreds
  namespace: ttx
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"user:token b64 encoded"}}}'